[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.0.5"
  export = ["donor_api"]
  name = "donor_api"
  org = "elixir"

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.27"
